### ISSUE TITLE
Problem the create app

### ISSUE THREAD

**Issue by XyDahn** [cdimascio/generator-express-no-stress#23] opened 2018-12-17 12:39 UTC
Hi, Whats up? 

I When create APP at the terminal return error the swagger/Api.yaml.
My solution is running process again and not allow the override.

Thanks!

**Comment by cdimascio** [comment] 2018-12-17 17:01
@XyDahn Thanks for the issue. Could you provide me the commands you ran, so that I can attempt reproduce the issue.

For example, it will be helpful if you can provide :
1. The command you ran that caused the error. (include any selections you made)
2. The output of the command you ran
3. The command you ran when it worked

Also, please include
1. `node --version`
2. `yo --version`

**Comment by XyDahn** [comment] 2018-12-17 17:25
Hi @cdimascio! =)
Follow information and printscreen:

1)   yo express-no-stress testapp --docker
2, 3) 
![image](https://user-images.githubusercontent.com/1986853/50103888-d0a8d000-020f-11e9-957f-447441fb5acf.png)

![image](https://user-images.githubusercontent.com/1986853/50103908-dc949200-020f-11e9-86e0-a7fdf47f5075.png)


debu.log:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint:fix' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prelint:fix', 'lint:fix', 'postlint:fix' ]
5 info lifecycle testapp@1.0.0~prelint:fix: testapp@1.0.0
6 info lifecycle testapp@1.0.0~lint:fix: testapp@1.0.0
7 verbose lifecycle testapp@1.0.0~lint:fix: unsafe-perm in lifecycle true
8 verbose lifecycle testapp@1.0.0~lint:fix: PATH: C:\Users\daniel.a.souza\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\daniel.a.souza\Downloads\generator-express-no-stress-master\testapp\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\app\daniel.a.souza\product\11.2.0\dbhome_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\apache-ant-1.9.9\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\daniel.a.souza\AppData\Local\Programs\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Users\daniel.a.souza\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\HashiCorp\Vagrant\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\daniel.a.souza\AppData\Local\Microsoft\WindowsApps;C:\Users\daniel.a.souza\AppData\Local\Programs\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Users\daniel.a.souza\AppData\Roaming\npm;C:\Users\daniel.a.souza\AppData\Local\Programs\Fiddler;C:\Users\daniel.a.souza\composer;C:\Users\daniel.a.souza\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Heroku\bin;C:\Users\daniel.a.souza\AppData\Local\Yarn\bin;C:\Users\daniel.a.souza\AppData\Local\Microsoft\WindowsApps;C:\Python27;C:\Python27\Scripts;C:\Users\daniel.a.souza\AppData\Local\Gpg4win\..\GnuPG\bin;C:\Users\daniel.a.souza\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\daniel.a.souza\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\daniel.a.souza\AppData\Local\ComposerSetup\bin;
9 verbose lifecycle testapp@1.0.0~lint:fix: CWD: C:\Users\daniel.a.souza\Downloads\generator-express-no-stress-master\testapp
10 silly lifecycle testapp@1.0.0~lint:fix: Args: [ '/d /s /c',
10 silly lifecycle   'eslint --fix -c .eslintrc.json {server,test}/**' ]
11 silly lifecycle testapp@1.0.0~lint:fix: Returned: code: 1  signal: null
12 info lifecycle testapp@1.0.0~lint:fix: Failed to exec lint:fix script
13 verbose stack Error: testapp@1.0.0 lint:fix: `eslint --fix -c .eslintrc.json {server,test}/**`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\daniel.a.souza\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\daniel.a.souza\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid testapp@1.0.0
15 verbose cwd C:\Users\daniel.a.souza\Downloads\generator-express-no-stress-master\testapp
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint:fix"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error testapp@1.0.0 lint:fix: `eslint --fix -c .eslintrc.json {server,test}/**`
22 error Exit status 1
23 error Failed at the testapp@1.0.0 lint:fix script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

node --version: v8.12.0
yo --version: 2.0.5

Thanks!

**Comment by cdimascio** [comment] 2018-12-17 18:03
Thank you! I see the issue. I will fix it once I'm at a computer. Should be done later today (note I'm in EST timezone)

**Comment by cdimascio** [comment] 2018-12-17 19:42
im unable to repro your issue. i am on mac not windows. 

the error, you pasted seems to indicate an error with the version string. that string looks valid as depicted in your screenshot (however, that assumes no hidden 'bad character' was input at the prompt). in any case, in the template, i now wrap quotes around the version, which should be robust to such inputs. 

give v5.1.2 a try. let me know your result.

**Comment by XyDahn** [comment] 2018-12-18 10:39
Hi @cdimascio, Thanks! 

Follow the new error: =/

![image](https://user-images.githubusercontent.com/1986853/50148753-7146d080-02a0-11e9-8a15-099edc468b13.png)

**Comment by XyDahn** [comment] 2018-12-18 11:36
Hi @cdimascio, I performed one test: 

`version: "<%= version %>"
  title: "<%= title %>"
  description: "<%= description %>"
basePath: "<%= apiRoot %>"`

But, return error for me:
![image](https://user-images.githubusercontent.com/1986853/50151547-5c6e3b00-02a8-11e9-8f6c-e4d093142b9d.png)

**Comment by cdimascio** [comment] 2018-12-18 23:13
@XyDahn The issue was due to eslint running on the yaml file. it is resolved in the latest version. Give it v.5.2.1 a try

**Comment by XyDahn** [comment] 2018-12-19 21:44
Hi @cdimascio, 

Follow new return error =/

![image](https://user-images.githubusercontent.com/1986853/50249872-6d14d300-03c6-11e9-9523-1e3bfaab7c2d.png)

**Comment by cdimascio** [comment] 2018-12-20 03:06
that error should be resolved. could you try to uninstall and reinstall generator-express-no-stress once more to ensure you have the latest version `5.2.2`
e.g.
```shell
> npm uninstall -g generator-express-no-stress
> /tmp npm install -g generator-express-no-stress
+ generator-express-no-stress@5.2.2 .    <--- ensure you get v5.2.2
added 314 packages from 227 contributors in 15.791s
```

This version should install an `.eslintignore` file that should ensure eslint does not attempt to lint the `*.yaml` files

**Comment by XyDahn** [comment] 2018-12-20 10:52
Hi @cdimascio.
The fix it ok! 

Very very Thank! =)

**Closed as completed** 2018-12-20 14:39 UTC
Labels: bug

**Comment by sotiris-oikonomou** [comment] 2019-04-10 15:53
I can confirm this happens on v7.0.1 as the .eslintignore file contains the .yaml extension and not the .yml extention the api.yml file is generated with.
